services:

  postgres:
    image: postgres:15
    container_name: service_registry_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service_registry

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always

volumes:
  postgres_data: